import { useMemo, useState, type FormEvent } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useApp } from '../store';
import { dateOffset, money, overlaps, paidAmount, paymentStatus, prettyDate, totalUnits, unitStatus, vendorCost, type Booking } from '../data';
import { Logo, Preferences } from '../components/Layout';
import { AdminHeading, DataTable, Metric, type Column } from '../components/AdminShared';
import { Badge, Button, EmptyState, Field, Icon, Select, Tabs } from '../components/ui';
import { BookingDetail, BookingEditor, newBooking } from './AdminBookings';

export function AdminLoginPage() {
  const { t, isAdmin, setIsAdmin, notify } = useApp(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const navigate = useNavigate(); const location = useLocation();
  if (isAdmin) return <Navigate to="/admin" replace />;
  function login(event: FormEvent) { event.preventDefault(); if (!['admin', 'admin@nusaride.id'].includes(email.trim().toLowerCase()) || password !== 'admin123') return notify(t('Gunakan akun demo: admin@nusaride.id / admin123.', 'Use the demo account: admin@nusaride.id / admin123.'), 'error'); setLoading(true); window.setTimeout(() => { setIsAdmin(true); notify(t('Selamat datang di NusaRide Workspace.', 'Welcome to NusaRide Workspace.')); const from = (location.state as { from?: string } | null)?.from; navigate(from?.startsWith('/admin') && from !== '/admin/login' ? from : '/admin', { replace: true }); }, 650); }
  return <div className="login-page"><div className="login-form-side"><header><Logo /><Preferences /></header><motion.div className="login-form-container" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}><span className="eyebrow">ADMIN WORKSPACE</span><h1>{t('Selamat datang kembali.', 'Welcome back.')}</h1><p>{t('Satu tempat untuk mengatur setiap perjalanan.', 'One place to keep every journey moving.')}</p><form onSubmit={login}><Field label={t('Email atau username', 'Email or username')} required><input type="text" required value={email} autoComplete="username" placeholder="admin@nusaride.id" onChange={event => setEmail(event.target.value)} /></Field><Field label="Password" required><div className="password-input"><input type={showPassword ? 'text' : 'password'} required value={password} autoComplete="current-password" placeholder={t('Masukkan password', 'Enter your password')} onChange={event => setPassword(event.target.value)} /><button type="button" className="icon-button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(!showPassword)}><Icon name={showPassword ? 'eye-crossed' : 'eye'} /></button></div></Field><Button type="submit" className="full-width" loading={loading}>{t('Masuk ke workspace', 'Sign in to workspace')}<Icon name="arrow-right" /></Button></form><div className="demo-login"><div><Icon name="flask" /><strong>{t('Coba dengan akun demo', 'Try the demo account')}</strong></div><p><span>admin@nusaride.id</span><span className="mono">admin123</span></p><button className="text-link" onClick={() => { setEmail('admin@nusaride.id'); setPassword('admin123'); notify(t('Akun demo sudah diisi. Klik Masuk untuk melanjutkan.', 'Demo credentials filled. Click Sign in to continue.'), 'info'); }}>{t('Isi akun demo', 'Use demo credentials')}<Icon name="arrow-right" /></button></div><p className="login-disclaimer"><Icon name="lock" />{t('Akses Super Admin saja. Autentikasi frontend simulasi, bukan keamanan produksi.', 'Super Admin access only. Simulated frontend authentication, not production security.')}</p><Link to="/" className="text-link"><Icon name="arrow-left" />{t('Kembali ke website', 'Back to website')}</Link></motion.div><footer>&copy; {new Date().getFullYear()} NusaRide Workspace</footer></div><div className="login-photo"><img src="/images/nusaride-hero.jpg" alt="NusaRide journey" /><div /><section><span className="hero-eyebrow">NUSARIDE FOR BUSINESS</span><h2>{t('Setiap perjalanan,\nterkendali.', 'Every journey,\nin good hands.')}</h2><p>{t('Armada, partner, dan pelanggan.\nTerhubung dalam satu workspace.', 'Vehicles, partners, and customers.\nConnected in one workspace.')}</p></section></div></div>;
}

export function AdminDashboard() {
  const { data, t, lang, notify } = useApp(); const navigate = useNavigate(); const [period, setPeriod] = useState('30'); const [chart, setChart] = useState('revenue'); const [hovered, setHovered] = useState<number | null>(null); const [viewId, setViewId] = useState<string | null>(null); const [editor, setEditor] = useState<Booking | null>(null);
  const today = dateOffset(); const rangeStart = dateOffset(-Number(period) + 1); const activeBookings = data.bookings.filter(b => b.status !== 'Cancelled'); const todayBookings = activeBookings.filter(b => overlaps(today, today, b.start, b.end)); const upcoming = activeBookings.filter(b => b.start > today && b.status !== 'Completed').sort((a, b) => a.start.localeCompare(b.start)); const inquiries = data.bookings.filter(b => b.status === 'Inquiry');
  const revenue = data.payments.filter(p => p.date >= rangeStart && p.date <= today).reduce((sum, p) => sum + (p.type === 'Refund' ? -p.amount : p.amount), 0);
  const profit = activeBookings.filter(b => b.start >= rangeStart && b.start <= today).reduce((sum, b) => sum + b.total - vendorCost(data, b), 0);
  const deposits = activeBookings.filter(b => paidAmount(data, b.id) > 0 && paidAmount(data, b.id) < b.total).reduce((sum, b) => sum + paidAmount(data, b.id), 0);
  const statuses = ['Available', 'Reserved', 'Booked', 'On Trip', 'Maintenance']; const colors = ['var(--text)', 'var(--neutral-500)', 'var(--info)', 'var(--positive)', 'var(--warning)']; const counts = statuses.map(status => data.units.filter(u => unitStatus(data, u) === status).length); const trackedTotal = counts.reduce((sum, n) => sum + n, 0);
  const chartValues = useMemo(() => Array.from({ length: 7 }, (_, index) => { const endOffset = -Math.floor((6 - index) * Number(period) / 7); const startOffset = -Math.floor((7 - index) * Number(period) / 7) + 1; const end = dateOffset(endOffset); const start = dateOffset(startOffset); const value = chart === 'revenue' ? data.payments.filter(p => p.date >= start && p.date <= end).reduce((sum, p) => sum + (p.type === 'Refund' ? -p.amount : p.amount), 0) : data.bookings.filter(b => b.status !== 'Cancelled' && b.start >= start && b.start <= end).reduce((sum, b) => sum + b.total - vendorCost(data, b), 0); return { date: end, value }; }), [data, period, chart]);
  const maxValue = Math.max(...chartValues.map(v => v.value), 1); const points = chartValues.map((v, index) => `${55 + index * 85},${173 - (v.value / maxValue) * 128}`).join(' '); const view = data.bookings.find(b => b.id === viewId);
  async function exportReport() { const { downloadReportPDF, bookingReportRows } = await import('../lib/pdf'); downloadReportPDF('Dashboard Summary', ['Booking', 'Customer', 'Date', 'Route', 'Status', 'Total', 'Paid', 'Profit'], bookingReportRows(data, activeBookings.filter(b => b.start >= rangeStart && b.start <= today)), `${prettyDate(rangeStart)} - ${prettyDate(today)}`); notify(t('Ringkasan dashboard diunduh.', 'Dashboard summary downloaded.')); }
  const columns: Column<Booking>[] = [
    { key: 'customer', label: 'Customer', render: b => <div className="table-person"><span className="avatar avatar-small">{b.name.split(' ').slice(0, 2).map(n => n[0]).join('')}</span><div><strong>{b.name}</strong><small>{b.code}</small></div></div> },
    { key: 'trip', label: t('Perjalanan', 'Trip'), render: b => <><strong>{b.destination}</strong><small>{prettyDate(b.start, lang)} &middot; {b.time}</small></> },
    { key: 'fleet', label: t('Armada', 'Fleet'), render: b => <><strong>{data.fleet.find(f => f.id === b.items[0]?.fleetId)?.name || '-'}</strong><small>{totalUnits(b.items)} unit</small></> },
    { key: 'status', label: 'Status', render: b => <Badge status={b.status}>{b.status}</Badge> },
    { key: 'action', label: '', render: b => <button className="icon-button" aria-label={t('Lihat booking', 'View booking')} onClick={() => setViewId(b.id)}><Icon name="arrow-up-right" /></button> },
  ];
  let offset = 0;
  return <><AdminHeading eyebrow={t('RINGKASAN WORKSPACE', 'WORKSPACE OVERVIEW')} title={t('Selamat datang, Admin.', 'Welcome back, Admin.')} description={t('Ini yang sedang terjadi di perjalanan NusaRide hari ini.', 'Here is what is happening across NusaRide today.')} actions={<><Button variant="secondary" onClick={exportReport}><Icon name="download" />{t('Unduh laporan', 'Download report')}</Button><Button onClick={() => setEditor(newBooking())}><Icon name="plus-small" />{t('Buat booking', 'Create booking')}</Button></>} />
    <div className="metrics-grid"><Metric label={t('Booking hari ini', "Today's bookings")} value={todayBookings.length} icon="calendar-check" note={t('Perjalanan aktif hari ini', 'Journeys scheduled today')} onClick={() => navigate('/admin/booking?today=1')} /><Metric label={t('Booking mendatang', 'Upcoming bookings')} value={upcoming.length} icon="calendar-clock" note={t('Sudah ada rencana berikutnya', 'More journeys on the horizon')} onClick={() => navigate('/admin/booking')} /><Metric label={t('Inquiry baru', 'Open inquiries')} value={inquiries.length} icon="comment-alt" note={t('Menunggu respons Anda', 'Waiting for your response')} onClick={() => navigate('/admin/booking?status=Inquiry')} /><Metric label={t('DP & pembayaran parsial', 'Deposits & partial payments')} value={money(deposits)} icon="wallet" note={t('Tercatat dalam simulasi', 'Recorded in the simulation')} onClick={() => navigate('/admin/pembayaran')} /></div>
    <div className="dashboard-middle"><section className="admin-panel revenue-panel"><div className="panel-heading"><div><h2>{t('Performa bisnis', 'Business performance')}</h2><p>{t('Gambaran keuangan perjalanan Anda.', 'A clear view of your journey finances.')}</p></div><Select value={period} onChange={setPeriod} options={[{ value: '7', label: t('7 hari terakhir', 'Last 7 days') }, { value: '30', label: t('30 hari terakhir', 'Last 30 days') }, { value: '90', label: t('90 hari terakhir', 'Last 90 days') }]} /></div><div className="revenue-totals"><div><span>{t('Pendapatan masuk', 'Revenue received')}</span><strong>{money(revenue)}</strong><small>{t('Berdasarkan pembayaran tercatat', 'Based on recorded payments')}</small></div><div><span>{t('Estimasi profit', 'Estimated profit')}</span><strong>{money(profit)}</strong><small>{t('Harga jual dikurangi modal vendor', 'Customer price minus vendor cost')}</small></div></div><Tabs value={chart} onChange={setChart} items={[{ value: 'revenue', label: t('Pendapatan', 'Revenue') }, { value: 'profit', label: t('Estimasi profit', 'Estimated profit') }]} /><div className="revenue-chart">{hovered !== null && <div className="chart-value-label">{prettyDate(chartValues[hovered].date, lang)}: <strong>{money(chartValues[hovered].value)}</strong></div>}<svg viewBox="0 0 620 215" role="img" aria-label={t('Grafik keuangan data demo', 'Demo financial chart')}>{[45, 88, 130, 173].map((y, i) => <g key={y}><line x1="52" x2="592" y1={y} y2={y} stroke="var(--border)" strokeDasharray="4 5" /><text x="1" y={y + 3} fontSize="9" fill="var(--text-muted)">{Math.round(maxValue * (1 - i / 3) / 1000000)}jt</text></g>)}<polygon points={`55,173 ${points} 565,173`} fill="var(--brand-soft)" opacity=".65" /><motion.polyline points={points} fill="none" stroke="var(--primary)" strokeWidth="2.7" strokeLinejoin="round" strokeLinecap="round" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: 1.2 }} />{chartValues.map((value, index) => <g key={index} onMouseEnter={() => setHovered(index)} onMouseLeave={() => setHovered(null)}><rect x={index * 85 + 20} y="18" width="75" height="165" fill="transparent" /><circle cx={55 + index * 85} cy={173 - value.value / maxValue * 128} r={hovered === index ? 5 : 3} fill="var(--surface)" stroke="var(--primary)" strokeWidth="2" /><text x={55 + index * 85} y="201" textAnchor="middle" fontSize="9" fill="var(--text-muted)">{new Date(value.date + 'T12:00:00').toLocaleDateString(lang === 'id' ? 'id-ID' : 'en-GB', { day: 'numeric', month: 'short' })}</text></g>)}</svg></div></section>
    <section className="admin-panel fleet-status-panel"><div className="panel-heading"><div><h2>{t('Status armada', 'Fleet status')}</h2><p>{t('Ketersediaan gabungan seluruh vendor.', 'Combined availability across vendors.')}</p></div><Link to="/admin/armada" className="icon-button" aria-label="View fleet"><Icon name="arrow-up-right" /></Link></div><div className="fleet-donut"><svg viewBox="0 0 190 190"><circle cx="95" cy="95" r="69" fill="none" stroke="var(--muted)" strokeWidth="18" />{counts.map((count, i) => { const dash = count / Math.max(1, trackedTotal) * 433.54; const current = offset; offset += dash; return <circle key={statuses[i]} cx="95" cy="95" r="69" fill="none" stroke={colors[i]} strokeWidth="18" strokeDasharray={`${Math.max(0, dash - 4)} ${433.54 - Math.max(0, dash - 4)}`} strokeDashoffset={-current} transform="rotate(-90 95 95)" />; })}</svg><div><strong>{data.units.length}</strong><span>{t('Total unit', 'Total vehicles')}</span></div></div><div className="fleet-legend">{statuses.map((status, i) => <button key={status} onClick={() => navigate(`/admin/armada?tab=units&status=${encodeURIComponent(status)}`)}><span style={{ background: colors[i] }} /><span>{status}</span><strong>{counts[i]}</strong><small>{Math.round(counts[i] / Math.max(1, data.units.length) * 100)}%</small></button>)}</div><div className="fleet-status-footer"><Link to="/admin/vendor"><strong>{data.vendors.length}</strong> {t('vendor partner', 'partner vendors')}<Icon name="arrow-up-right" /></Link><Link to="/admin/armada"><strong>{data.fleet.length}</strong> {t('tipe armada', 'vehicle types')}<Icon name="arrow-up-right" /></Link></div></section></div>
    <div className="dashboard-bottom"><section className="admin-panel upcoming-panel"><div className="panel-heading"><div><h2>{t('Perjalanan berikutnya', 'Up next')}</h2><p>{t('Pastikan semuanya siap sebelum berangkat.', 'Make sure everything is ready before departure.')}</p></div><Link className="text-link" to="/admin/booking">{t('Lihat semua', 'View all')}<Icon name="arrow-right" /></Link></div><DataTable columns={columns} rows={upcoming.slice(0, 5)} onRowClick={b => setViewId(b.id)} /></section><section className="admin-panel inquiry-panel"><div className="panel-heading"><div><h2>{t('Perlu perhatian', 'Needs attention')}</h2><p>{t('Rencana yang menunggu langkah Anda.', 'Plans waiting for your next move.')}</p></div><span className="inquiry-count">{inquiries.length}</span></div>{inquiries.length ? <div className="inquiry-list">{inquiries.slice(0, 3).map(b => <button key={b.id} onClick={() => setViewId(b.id)}><span className="inquiry-type-icon"><Icon name={b.customerType === 'Personal' ? 'user' : 'building'} /></span><div><strong>{b.company || b.name}</strong><p>{b.destination} &middot; {b.passengers} {t('orang', 'people')}</p><small>{totalUnits(b.items)} unit &middot; {prettyDate(b.start, lang)}</small></div><Icon name="angle-small-right" /></button>)}</div> : <EmptyState title={t('Semua sudah ditangani', 'All caught up')} description={t('Belum ada inquiry baru.', 'No new inquiries.')} icon="check-circle" />}<Link className="inquiry-footer" to="/admin/corporate-request">{t('Kelola corporate request', 'Manage corporate requests')}<Icon name="arrow-right" /></Link><div className="mini-overview"><span>{t('Booking lunas', 'Fully paid bookings')}<strong>{activeBookings.filter(b => paymentStatus(data, b) === 'Lunas').length}</strong></span><span>{t('Corporate request', 'Corporate requests')}<strong>{activeBookings.filter(b => b.customerType !== 'Personal' || totalUnits(b.items) >= 3).length}</strong></span></div></section></div>
    {view && <BookingDetail booking={view} onClose={() => setViewId(null)} onEdit={() => { setEditor(view); setViewId(null); }} />}{editor && <BookingEditor initial={editor} onClose={() => setEditor(null)} />}
  </>;
}