import { useState } from 'react';
import { Link } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { useApp } from '../store';
import { whatsappUrl } from '../data';
import { CategoryTabs, HeroSearchForm, VehicleCard } from '../components/Fleet';
import { Icon, Reveal } from '../components/ui';

export const faqData = [
  { id: 'Bagaimana cara rental di NusaRide?', en: 'How do I rent with NusaRide?', answerId: 'Pilih tanggal, lokasi, dan jumlah penumpang, lalu cari armada yang tersedia. Anda bisa memilih satu atau beberapa kendaraan, mengisi data pemesan, kemudian konsultasi terlebih dahulu atau melakukan simulasi DP Rp50.000.', answerEn: 'Choose your dates, pickup location, and passenger count, then find available vehicles. Select one or more vehicles, fill in your details, and either request a consultation or simulate a Rp50,000 deposit.' },
  { id: 'Apakah bisa sewa mobil lepas kunci?', en: 'Can I rent a self-drive vehicle?', answerId: 'Bisa. Toyota Avanza Veloz dan Toyota Innova Zenix tersedia untuk lepas kunci atau dengan driver. Hiace, Elf, Medium Bus, dan Big Bus wajib menggunakan driver. Rombongan lebih dari 8 orang tetap boleh memilih kombinasi beberapa mobil lepas kunci.', answerEn: 'Yes. The Toyota Avanza Veloz and Innova Zenix are available for self-drive or with a driver. Hiace, Elf, Medium Bus, and Big Bus require a driver. Groups of more than 8 may still rent multiple self-drive cars.' },
  { id: 'Bolehkah menggabungkan beberapa jenis armada?', en: 'Can I combine different vehicle types?', answerId: 'Tentu. Anda dapat mengombinasikan Mobil, Hiace, Elf, Medium Bus, dan Big Bus serta menentukan jumlah unit masing-masing. Total kapasitas akan dihitung otomatis agar sesuai kebutuhan rombongan Anda.', answerEn: 'Absolutely. Combine cars, Hiace, Elf, Medium Bus, and Big Bus and choose the number of each. Total seating capacity is calculated automatically to suit your group.' },
  { id: 'Bagaimana cara mendapatkan harga corporate / group?', en: 'How do I get corporate or group pricing?', answerId: 'Harga khusus tersedia untuk pemesanan minimal 3 unit, boleh kombinasi semua kategori. Berlaku untuk perusahaan, sekolah, instansi, travel agent, event organizer, dan personal. Harga final diberikan melalui penawaran, dilengkapi quotation dan invoice.', answerEn: 'Special pricing is available for bookings of 3 or more vehicles, including mixed categories. Companies, schools, institutions, travel agents, event organizers, and individuals all qualify. Final pricing is provided in a formal quotation with invoicing.' },
  { id: 'Apa saja yang sudah termasuk dalam harga rental?', en: 'What is included in the rental price?', answerId: 'Harga dasar meliputi penggunaan kendaraan per hari. Untuk Hiace, Elf, dan bus sudah termasuk driver. Driver mobil dikenakan tambahan Rp200.000 per hari. BBM, tol, parkir, makan, dan penginapan driver belum termasuk kecuali tercantum dalam penawaran.', answerEn: 'Base prices cover daily vehicle use. Hiace, Elf, and buses include a driver. Car drivers cost an additional Rp200,000 per day. Fuel, tolls, parking, driver meals, and accommodation are not included unless specified in your quotation.' },
  { id: 'Apakah pembayaran di website ini sungguhan?', en: 'Are payments on this website real?', answerId: 'Tidak. Website NusaRide ini adalah demo frontend. Seluruh kendaraan, booking, kontak, dan pembayaran merupakan simulasi. Data disimpan hanya di browser Anda, tidak ada database atau transaksi dana sungguhan.', answerEn: 'No. This NusaRide website is a frontend demo. All vehicles, bookings, contacts, and payments are simulated. Data is stored only in your browser. There is no database or real financial transaction.' },
];

export function FAQ({ standalone = false }: { standalone?: boolean }) {
  const { t } = useApp(); const [active, setActive] = useState<number | null>(0);
  return <section className={`faq-section section-space ${standalone ? 'container' : ''}`} id="faq"><div className="container faq-layout"><Reveal className="faq-heading"><span className="eyebrow">{t('ADA PERTANYAAN?', 'GOOD TO KNOW')}</span><h2>{t('Jawaban sebelum\nperjalanan.', 'A little clarity,\nbefore you go.')}</h2><p>{t('Hal-hal yang mungkin ingin Anda ketahui sebelum berangkat bersama kami.', 'A few things you might want to know before hitting the road with us.')}</p><a className="text-link" href={whatsappUrl('Halo NusaRide, saya punya pertanyaan mengenai rental. (Demo)')} target="_blank" rel="noreferrer">{t('Tanyakan hal lainnya', 'Ask us anything else')}<Icon name="arrow-up-right" /></a></Reveal><div className="faq-list">{faqData.map((item, index) => <div className={`faq-item ${active === index ? 'faq-active' : ''}`} key={item.id}><button onClick={() => setActive(active === index ? null : index)} aria-expanded={active === index} aria-controls={`faq-${index}`}><span className="faq-number">0{index + 1}</span><span>{t(item.id, item.en)}</span><Icon name={active === index ? 'minus-small' : 'plus-small'} /></button><AnimatePresence>{active === index && <motion.div className="faq-answer" id={`faq-${index}`} initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}><p>{t(item.answerId, item.answerEn)}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>;
}
export function HomePage() {
  const { t, data } = useApp(); const [category, setCategory] = useState('all');
  const vehicles = data.fleet.filter(fleet => fleet.active && (category === 'all' || fleet.category === category)).slice(0, 4);
  return <>
    <section className="hero">
      <picture className="hero-picture"><source media="(max-width: 640px)" srcSet="/images/mobile-hero.webp" /><motion.img className="hero-image" src="/images/desktop-hero.webp" alt={t('Toyota Innova Zenix di jalan pesisir Indonesia', 'Toyota Innova Zenix on an Indonesian coastal road')} initial={{ scale: 1.055 }} animate={{ scale: 1 }} transition={{ duration: 1.8, ease: 'easeOut' }} fetchPriority="high" /></picture>
      <div className="hero-shade" />
      <div className="container hero-inner"><motion.div className="hero-content" initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .15 }}>
        <span className="hero-eyebrow"><span />{t('RENTAL MOBIL LEPAS KUNCI & DRIVER', 'SELF-DRIVE & CHAUFFEURED RENTALS')}</span>
        <h1>{t('Ke mana pun.', 'Wherever you go.')}<br />{t('Bersama', 'Go with')} <em>NusaRide.</em></h1>
        <p>{t('Mobil matic dan armada dengan driver untuk Jabodetabek hingga luar kota. Pilih jadwal, lihat estimasi, lalu ajukan booking tanpa pembayaran di awal.', 'Self-drive cars and chauffeured vehicles across Greater Jakarta and beyond. Choose your schedule, see an estimate, and request a booking without paying upfront.')}</p>
        <Link className="hero-secondary" to="/corporate">{t('Perlu sewa korporat atau beberapa unit?', 'Need corporate rental or multiple vehicles?')}<Icon name="arrow-right" /></Link>
      </motion.div><HeroSearchForm /></div>
    </section>
    <section className="fleet-section section-space" id="armada"><div className="container"><Reveal className="section-heading"><div><span className="eyebrow">{t('PILIHAN ARMADA', 'FIND YOUR PERFECT RIDE')}</span><h2>{t('Beda kebutuhan, satu tujuan.', 'Different journeys. One destination.')}</h2><p>{t('Sendiri, bersama keluarga, atau satu rombongan. Kami punya pilihannya.', 'Solo trips, family getaways, or the whole team. We have a ride for you.')}</p></div><Link className="text-link" to="/armada">{t('Lihat semua armada', 'Explore all vehicles')}<Icon name="arrow-up-right" /></Link></Reveal><div className="fleet-tabs-row"><CategoryTabs value={category} onChange={setCategory} /><span className="fleet-note"><span />{t('Terawat. Bersih. Siap jalan.', 'Well maintained. Clean. Ready to go.')}</span></div><div className="fleet-grid">{vehicles.map((fleet, index) => <Reveal key={fleet.id} delay={index * .065}><VehicleCard fleet={fleet} /></Reveal>)}</div><div className="fleet-bottom-note"><Icon name="info" /><span>{t('Punya rombongan besar? Kombinasikan beberapa armada sesuai kebutuhan Anda.', 'Traveling with a bigger group? Mix and match vehicles to fit your plans.')}</span><Link to="/armada?combine=1">{t('Atur kombinasi', 'Build your fleet')}<Icon name="arrow-right" /></Link></div></div></section>
    <section className="promise-section" id="tentang"><div className="container"><Reveal className="promise-intro"><span className="eyebrow">{t('PERJALANAN YANG LEBIH BAIK', 'A BETTER WAY TO TRAVEL')}</span><h2>{t('Anda nikmati perjalanannya.\nBiar kami urus kendaraannya.', 'You enjoy the journey.\nWe take care of the ride.')}</h2></Reveal><div className="promise-grid">{[{ n: '01', title: t('Armada untuk setiap rencana', 'A ride for every plan'), body: t('Dari mobil keluarga hingga bus pariwisata. Satu tempat untuk semua kebutuhan transportasi.', 'From family cars to touring coaches. One place for all your transport needs.'), icon: 'car-alt' }, { n: '02', title: t('Harga jelas, tanpa kejutan', 'Clear prices. No surprises.'), body: t('Lihat estimasi sejak awal. Pilih lepas kunci atau driver, sesuaikan dengan cara Anda bepergian.', 'See an estimate from the start. Choose self-drive or a driver and travel your way.'), icon: 'shield-check' }, { n: '03', title: t('Ada untuk membantu Anda', 'Real people, ready to help'), body: t('Tim kami siap menemani dari perencanaan hingga tiba di tujuan. Cukup satu pesan WhatsApp.', 'We are here from your first plan to your final destination. Just a WhatsApp message away.'), icon: 'headset' }].map(item => <Reveal className="promise-item" key={item.n}><div><Icon name={item.icon} /><span>{item.n}</span></div><h3>{item.title}</h3><p>{item.body}</p></Reveal>)}</div></div></section>
    <section className="packages-section section-space"><div className="container"><Reveal className="section-heading"><div><span className="eyebrow">{t('DIRENCANAKAN UNTUK ANDA', 'MADE FOR YOUR PLANS')}</span><h2>{t('Tinggal pilih, lalu berangkat.', 'Pick your plan. Hit the road.')}</h2><p>{t('Pilihan paket yang memudahkan setiap agenda perjalanan.', 'Thoughtful packages that make every trip a little easier.')}</p></div><Link className="text-link" to="/paket">{t('Jelajahi paket', 'Explore packages')}<Icon name="arrow-up-right" /></Link></Reveal><div className="package-lines">{[{ no: '01', title: t('Harian & dalam kota', 'Daily & city rides'), desc: t('Untuk agenda kerja, urusan pribadi, dan keseharian Anda.', 'For workdays, errands, and everything in between.'), detail: t('Mulai Rp400.000 / hari', 'From Rp400,000 / day'), to: '/paket?type=daily', icon: 'car-alt' }, { no: '02', title: t('Liburan & luar kota', 'Getaways & road trips'), desc: t('Waktu berkualitas, destinasi baru, kenangan yang lebih banyak.', 'Quality time, new places, and memories worth keeping.'), detail: t('Paket multi-day tersedia', 'Multi-day packages available'), to: '/paket?type=holiday', icon: 'mountains' }, { no: '03', title: t('Airport transfer', 'Airport transfers'), desc: t('Tepat waktu untuk keberangkatan. Nyaman saat kedatangan.', 'On time for departures. A warm welcome on arrival.'), detail: t('One way & pulang pergi', 'One way & round trip'), to: '/paket?type=airport', icon: 'plane-alt' }].map(item => <Reveal key={item.no}><Link className="package-line" to={item.to}><span className="package-number">{item.no}</span><span className="package-icon"><Icon name={item.icon} /></span><div><h3>{item.title}</h3><p>{item.desc}</p></div><span className="package-detail">{item.detail}</span><span className="round-arrow"><Icon name="arrow-up-right" /></span></Link></Reveal>)}</div></div></section>
    <section className="corporate-feature"><div className="corporate-feature-image"><img src="/images/corporate.webp" alt={t('Armada NusaRide di depan gedung perkantoran modern', 'NusaRide corporate transport outside a modern office')} loading="lazy" /></div><div className="corporate-feature-content"><Reveal><span className="eyebrow">CORPORATE & GROUP</span><h2>{t('Rencana besar.\nPerjalanan lebih mudah.', 'Big plans.\nEffortless journeys.')}</h2><p>{t('Transportasi untuk tim, acara, dan semua yang Anda rencanakan bersama. Kombinasikan armada dengan harga khusus mulai 3 unit.', 'Transport for teams, events, and everything you plan together. Mix and match vehicles with special pricing from 3 units.')}</p><ul><li><Icon name="check" />{t('Fleksibel memilih & mengombinasikan armada', 'Flexible vehicle choices and combinations')}</li><li><Icon name="check" />{t('Quotation & invoice untuk kebutuhan bisnis', 'Quotations and invoices for your business')}</li><li><Icon name="check" />{t('Satu PIC, koordinasi lebih sederhana', 'One point of contact. Simpler coordination.')}</li></ul><Link className="btn btn-primary" to="/corporate">{t('Kenali layanan corporate', 'Explore corporate rentals')}<Icon name="arrow-up-right" /></Link></Reveal></div></section>
    <FAQ />
    <section className="closing-cta"><div className="container"><Reveal><span className="eyebrow">{t('PERJALANAN ANDA BERIKUTNYA', 'YOUR NEXT CHAPTER')}</span><h2>{t('Ada rencana ke mana?', 'Where to next?')}</h2><p>{t('Ceritakan rencana Anda. Kami bantu temukan perjalanan terbaiknya.', "Tell us what you have in mind. We'll help you get there.")}</p><a className="btn btn-primary" href={whatsappUrl('Halo NusaRide, saya ingin merencanakan perjalanan. (Demo)')} target="_blank" rel="noreferrer"><Icon name="comment-alt" />{t('Rencanakan via WhatsApp', 'Plan your trip on WhatsApp')}<Icon name="arrow-up-right" /></a></Reveal><svg className="cta-road" viewBox="0 0 300 300" fill="none" aria-hidden="true"><path d="M350 280C170 280 260 90 100 90S-50 10-50-30" stroke="currentColor" strokeWidth="58" /><path d="M350 280C170 280 260 90 100 90S-50 10-50-30" stroke="var(--surface)" strokeWidth="2" strokeDasharray="12 12" /></svg></div></section>
  </>;
}
