import { type ReactNode } from 'react';
import { useApp } from '../store';
import { EmptyState, Icon } from './ui';

export function AdminHeading({ title, description, actions, eyebrow }: { title: string; description: string; actions?: ReactNode; eyebrow?: string }) {
  return <div className="admin-page-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{description}</p></div>{actions && <div className="admin-heading-actions">{actions}</div>}</div>;
}
export interface Column<T> { key: string; label: string; render: (row: T) => ReactNode; className?: string }
export function DataTable<T extends { id: string }>({ columns, rows, onRowClick, emptyAction }: { columns: Column<T>[]; rows: T[]; onRowClick?: (row: T) => void; emptyAction?: ReactNode }) {
  const { t } = useApp(); return rows.length ? <div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(col => <th key={col.key} className={col.className}>{col.label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className={onRowClick ? 'clickable-row' : ''} onClick={() => onRowClick?.(row)}>{columns.map(col => <td key={col.key} className={col.className}>{col.render(row)}</td>)}</tr>)}</tbody></table></div> : <EmptyState title={t('Belum ada data yang cocok', 'No matching records')} description={t('Coba kata kunci atau filter lain, atau tambahkan data baru.', 'Try another search or filter, or add a new record.')} action={emptyAction} icon="folder-open" />;
}
export function TableSearch({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder?: string }) { const { t } = useApp(); return <div className="table-search"><Icon name="search" /><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder || t('Cari data...', 'Search records...')} aria-label={placeholder || t('Cari data', 'Search records')} />{value && <button className="icon-button" onClick={() => onChange('')} aria-label={t('Hapus pencarian', 'Clear search')}><Icon name="cross-small" /></button>}</div>; }
export function Metric({ label, value, icon, note, trend, onClick }: { label: string; value: string | number; icon: string; note?: string; trend?: string; onClick?: () => void }) { return <button className="metric" onClick={onClick} disabled={!onClick}><div className="metric-top"><span>{label}</span><Icon name={icon} /></div><strong>{value}</strong><div className="metric-bottom">{trend && <span><Icon name="arrow-trend-up" />{trend}</span>}{note && <small>{note}</small>}{onClick && <Icon name="arrow-up-right" />}</div></button>; }
export function TableActions({ onView, onEdit, onDelete, extra }: { onView?: () => void; onEdit?: () => void; onDelete?: () => void; extra?: ReactNode }) { const { t } = useApp(); return <div className="table-actions" onClick={event => event.stopPropagation()}>{onView && <button className="icon-button" aria-label={t('Lihat detail', 'View details')} title={t('Lihat detail', 'View details')} onClick={onView}><Icon name="eye" /></button>}{onEdit && <button className="icon-button" aria-label={t('Edit data', 'Edit record')} title={t('Edit data', 'Edit record')} onClick={onEdit}><Icon name="pencil" /></button>}{extra}{onDelete && <button className="icon-button delete-button" aria-label={t('Hapus data', 'Delete record')} title={t('Hapus data', 'Delete record')} onClick={onDelete}><Icon name="trash" /></button>}</div>; }